# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-08 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luftdaten', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensorvalue',
            name='signal',
            field=models.CharField(max_length=10),
        ),
    ]
