# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-08 12:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luftdaten', '0002_auto_20170208_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensorvalue',
            name='SDS_P1',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='sensorvalue',
            name='SDS_P2',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='sensorvalue',
            name='humidity',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='sensorvalue',
            name='temperature',
            field=models.FloatField(null=True),
        ),
    ]
