# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-10 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luftdaten', '0003_auto_20170208_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensorvalue',
            name='device',
            field=models.CharField(db_index=True, default='0', max_length=100),
            preserve_default=False,
        ),
    ]
