# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-11 18:48
from __future__ import unicode_literals
from django.db import migrations
from django.utils import timezone


def offset_tz(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    SensorValueAggregated = apps.get_model('luftdaten', 'SensorValueAggregated')
    for value in SensorValueAggregated.objects.all():
        value.date = value.date + timezone.timedelta(hours=1)
        value.save()


class Migration(migrations.Migration):

    dependencies = [
        ('luftdaten', '0005_sensorvalueaggregated'),
    ]

    operations = [
        migrations.RunPython(offset_tz),
    ]
