# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-30 15:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nsfw', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PM10',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('date', models.DateField()),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nsfw.Station')),
            ],
        ),
    ]
