# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-01 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nsfw', '0002_pm10'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pm10',
            options={'verbose_name': 'PM10', 'verbose_name_plural': 'PM10'},
        ),
        migrations.AddField(
            model_name='station',
            name='lat',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='station',
            name='lon',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
