# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-01 19:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nsfw', '0003_auto_20160701_1525'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField()),
                ('kind', models.CharField(choices=[('PM1', 'PM10'), ('NO2', 'NO2')], max_length=3)),
                ('date', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='pm10',
            name='station',
        ),
        migrations.DeleteModel(
            name='PM10',
        ),
    ]
