# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-01 20:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nsfw', '0004_auto_20160701_1950'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=10, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('report', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nsfw.Report')),
                ('station', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nsfw.Station')),
            ],
        ),
    ]
