# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-01 20:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nsfw', '0005_alert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='value',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
