# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-04 14:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nsfw', '0008_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='email',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AddField(
            model_name='subscription',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nsfw.Email'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nsfw.Station'),
        ),
    ]
