# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 11:43
from __future__ import unicode_literals

from django.db import migrations
import html


def remove_html(apps, schema_editor):
    Station = apps.get_model("nsfw", "Station")
    for station in Station.objects.all():
        station.name = html.unescape(station.name)
        print(station.name)
        station.save()


class Migration(migrations.Migration):

    dependencies = [
        ('nsfw', '0010_auto_20160704_1710'),
    ]

    operations = [
        migrations.RunPython(remove_html),
    ]
