# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-27 07:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nsfw', '0011_auto_20160713_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
