# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-27 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nsfw', '0013_auto_20160727_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='no2_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
