# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-23 15:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messenger_bot', '0001_initial'),
        ('nsfw', '0014_station_no2_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='messenger',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='messenger_bot.Messenger'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='email',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nsfw.Email'),
        ),
    ]
