# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-08 11:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nsfw', '0015_auto_20161123_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='email',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nsfw.Email'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='messenger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='messenger_bot.Messenger'),
        ),
    ]
