# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-14 09:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nsfw', '0016_report_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='country',
            field=models.CharField(default='de', max_length=2),
            preserve_default=False,
        ),
    ]
