# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-14 16:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nsfw', '0016_auto_20170208_1253'),
        ('nsfw', '0017_report_country'),
    ]

    operations = [
    ]
